on:
  push:
    branches:
      - main

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1
        with:
          secret_input: ${{ secrets.OPENFN_2976948c_b8c4_4cdc_9f7f_176d4312a18e_API_KEY }}
          config_path_input: 'openfn-2976948c-b8c4-4cdc-9f7f-176d4312a18e-config.json'
